### ISSUE TITLE
Hello, I make build, but something errors, Would you know that ?

### ISSUE THREAD

**Issue by timloo0710** [phao/tetris#1]
My env is ubuntu gcc, 

thank you 

$ make build
gcc -Wall -Wextra -Werror -std=c99 -pedantic -pipe -g3 -DSDL_ASSERT_LEVEL=3 -O0 -c main.c
gcc -Wall -Wextra -Werror -std=c99 -pedantic -pipe -g3 -DSDL_ASSERT_LEVEL=3 -O0 -c menu.c
gcc -Wall -Wextra -Werror -std=c99 -pedantic -pipe -g3 -DSDL_ASSERT_LEVEL=3 -O0 -c error.c
error.c:83:1: error: unknown type name ‘ErrorInfo’
 ErrorInfo*
 ^
error.c:84:1: error: conflicting types for ‘get_error’
 get_error(void) {
 ^
In file included from error.c:5:0:
error.h:33:1: note: previous declaration of ‘get_error’ was here
 get_error(void);
 ^
error.c: In function ‘get_error’:
error.c:93:10: error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
   return out;
          ^
error.c: In function ‘free_error’:
error.c:103:5: error: unknown type name ‘ErrorInfo’
     ErrorInfo _aux = err->next;
     ^
error.c:103:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
     ErrorInfo *aux = err->next;
                      ^
error.c:109:9: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     err = aux;
         ^
cc1: all warnings being treated as errors
Makefile:15: recipe for target 'error.o' failed
make: *_\* [error.o] Error 1

**Comment by phao** [comment]
It seemed I had an invalid version of the source code in the github repo... That's weird...

I've pushed my local version.

Care to try updating your local version?

It has been a while since I last looked at this project and I'm quite busy these days, so I can't promise I'll be able to look at your issue much further.

It seems like just re-pulling (or re-cloning) should work.

Sorry for this. 

(Besides, I don't know much about git and/or github.)

**Comment by phao** [comment]
Forgot to close it back then.
